// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAps4XeB2k4IqODwpe2tbUkdpYqqzjMrQU',
    appId: '1:869648216540:web:17f7f41606edc9a7b29f19',
    messagingSenderId: '869648216540',
    projectId: 'flutter-freecodecamp-course',
    authDomain: 'flutter-freecodecamp-course.firebaseapp.com',
    storageBucket: 'flutter-freecodecamp-course.firebasestorage.app',
    measurementId: 'G-Z8M6VMY1EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWPb_XE2qLnsjmWnJ7GjqCnIoNMwEqV0E',
    appId: '1:869648216540:android:4bd809b0d13544d6b29f19',
    messagingSenderId: '869648216540',
    projectId: 'flutter-freecodecamp-course',
    storageBucket: 'flutter-freecodecamp-course.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07lnKEeOEQ-Ienef-TiqLOAqLVDKcj9E',
    appId: '1:869648216540:ios:6a9cca03cc64019bb29f19',
    messagingSenderId: '869648216540',
    projectId: 'flutter-freecodecamp-course',
    storageBucket: 'flutter-freecodecamp-course.firebasestorage.app',
    iosBundleId: 'com.example.freecodecampFlutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07lnKEeOEQ-Ienef-TiqLOAqLVDKcj9E',
    appId: '1:869648216540:ios:6a9cca03cc64019bb29f19',
    messagingSenderId: '869648216540',
    projectId: 'flutter-freecodecamp-course',
    storageBucket: 'flutter-freecodecamp-course.firebasestorage.app',
    iosBundleId: 'com.example.freecodecampFlutterCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAps4XeB2k4IqODwpe2tbUkdpYqqzjMrQU',
    appId: '1:869648216540:web:9746124cb685734fb29f19',
    messagingSenderId: '869648216540',
    projectId: 'flutter-freecodecamp-course',
    authDomain: 'flutter-freecodecamp-course.firebaseapp.com',
    storageBucket: 'flutter-freecodecamp-course.firebasestorage.app',
    measurementId: 'G-T7DWXLWTRT',
  );
}
